status = [
	"continuous-integration/travis-ci/push",
	"clap-rs.clap",
]
pr_status = [
	"continuous-integration/travis-ci/pr",
	"clap-rs.clap",
]
timeout_sec = 7200
prerun_timeout_sec = 7200
delete_merged_branches = true
cut_body_after = "\n\n"
block_lables = ["R: blocked", "R: require changes"]
