name: CI
on:
  push:
    branches: [staging, trying]
concurrency:
    group: ci-${{ github.ref}}
    cancel-in-progress: true
jobs:
  ci:
    name: CI
    needs: [test, wasm]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  args:
    name: Args
    runs-on: ubuntu-latest
    outputs:
      minimal: ${{ steps.minimal.outputs.list }}
      full: ${{ steps.full.outputs.list }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: minimal
        name: Get args (Minimal)
        run: echo "::set-output name=list::$(make features-minimal)"
      - id: full
        name: Get args (Full)
        run: echo "::set-output name=list::$(make features-full)"
  test:
    name: Tests
    needs: [args]
    strategy:
      fail-fast: false
      matrix:
        features: [minimal, full, release]
        rust: [1.54.0, stable, beta]
        os: [windows-latest, macos-latest, ubuntu-latest]
        target:
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
          - i686-pc-windows-gnu
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-apple-darwin
        exclude:
          - features: release
            rust: stable
          - features: release
            rust: beta
          - os: windows-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: i686-unknown-linux-gnu
          - os: macos-latest
            target: i686-pc-windows-msvc
          - os: macos-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: i686-pc-windows-gnu
          - os: macos-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: i686-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: i686-pc-windows-gnu
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
          - os: ubuntu-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install linker
        if: matrix.target == 'i686-pc-windows-gnu'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
      - name: Install linker
        if: matrix.target == 'x86_64-pc-windows-gnu'
        uses: egor-tensin/setup-mingw@v2
      - name: Install linker
        if: matrix.target == 'i686-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Cache Builds
        uses: Swatinem/rust-cache@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test (Minimal)
        uses: actions-rs/cargo@v1
        if: matrix.features == 'minimal'
        with:
          command: test
          args: --target ${{ matrix.target }} ${{ needs.args.outputs.minimal }}
      - name: Test (Full)
        uses: actions-rs/cargo@v1
        if: matrix.features == 'full'
        with:
          command: test
          args: --target ${{ matrix.target }} ${{ needs.args.outputs.full }}
      - name: Check debug
        uses: actions-rs/cargo@v1
        if: matrix.features == 'full'
        with:
          command: check
          args: --target ${{ matrix.target }} ${{ needs.args.outputs.full }} --features debug
      - name: Test (Release)
        uses: actions-rs/cargo@v1
        if: matrix.features == 'release'
        with:
          command: test
          args: --target ${{ matrix.target }} ${{ needs.args.outputs.full }} --release
  nightly:
    name: Nightly Tests
    needs: [args]
    strategy:
      fail-fast: false
      matrix:
        features:
          - minimal
          - full
          - release
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test (Minimal)
        uses: actions-rs/cargo@v1
        if: matrix.features == 'minimal'
        with:
          command: test
          args: ${{ needs.args.outputs.minimal }}
      - name: Test (Full)
        uses: actions-rs/cargo@v1
        if: matrix.features == 'full'
        with:
          command: test
          args: ${{ needs.args.outputs.full }}
      - name: Check debug
        uses: actions-rs/cargo@v1
        if: matrix.features == 'full'
        with:
          command: check
          args: ${{ needs.args.outputs.full }} --features debug
      - name: Test release
        uses: actions-rs/cargo@v1
        if: matrix.features == 'release'
        with:
          command: test
          args: ${{ needs.args.outputs.full }} --release
  wasm:
    name: Wasm Check
    needs: [args]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [wasm32-unknown-unknown, wasm32-wasi]
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.54.0
          target: ${{ matrix.target }}
          override: true
      - name: Cache Builds
        uses: Swatinem/rust-cache@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check (Minimal)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target ${{ matrix.target }} ${{ needs.args.outputs.minimal }}
      - name: Check (Full)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target ${{ matrix.target }} ${{ needs.args.outputs.full }}
