name: Lint
on:
  pull_request:
    branches: [master]
  push:
    branches: [staging, trying]
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  args:
    name: Args
    runs-on: ubuntu-latest
    outputs:
      minimal: ${{ steps.minimal.outputs.list }}
      full: ${{ steps.full.outputs.list }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: minimal
        name: Get args (Minimal)
        run: echo "::set-output name=list::$(make features-minimal)"
      - id: full
        name: Get args (Full)
        run: echo "::set-output name=list::$(make features-full)"
  lint:
    name: Lint
    needs: [args]
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Cache Builds
        uses: Swatinem/rust-cache@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clippy (Minimal)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ needs.args.outputs.minimal }} -- -D warnings
      - name: Clippy (Full)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ needs.args.outputs.full }} -- -D warnings
      - name: Format check
        run: make fmt-check
